module.exports = {
  PARAM_ESTADO_OK: 'OK',
  PARAM_ESTADO_NOK: 'NOK',
  PARAM_ESTADO_ACTIVO: '1',
  PARAM_ESTADO_NO_ACTIVO: '0',
  PARAM_MENSAJE_QUERY: 'CONSULTA EJECUTADA CON EXITO',
  PARAM_MENSAJE_ERROR: 'ERROR AL EJECUTAR LA CONSULTA'
}
